{{- $containerType :=  required "container.type is required. Possible values: api, worker." .Values.container.type }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abc.fullname" . }}
  labels:
    {{- include "abc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "abc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "abc.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{- required "image.repository is required." .Values.image.repository }}:{{- required "image.tag is required." .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: APP_NAME
            value: {{ include "abc.fullname" . }}
          {{- toYaml .Values.container.env | nindent 10 }}
          {{- if eq $containerType "api" }}
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ include "abc.dotnetEnvironment" . }}
          {{- end }}
          {{- if eq $containerType "worker" }}
          - name: DOTNET_ENVIRONMENT
            value: {{ include "abc.dotnetEnvironment" . }}
          {{- end }}  
          envFrom:
          {{- toYaml .Values.container.envFrom | nindent 10 }}
          {{- if eq $containerType "api" }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      nodeSelector:
        agentpool : {{ required "env is required. Possible values: dev, prod." .Values.env }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
