apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: infra
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./external
  prune: true
  wait: true
  timeout: 2m0s