parameters:
- name: workingDirectory
  type: string
- name: testsDirectory
  type: string  
  default: ''
- name: efMigrations
  type: object
  default:
    enabled: false

variables:
  - template: base/variables.yml

stages:
- stage: Main
  displayName: Build and publish
    
  jobs:
  - job: Main
    displayName: Build and publish

    steps:
    - task: UseDotNet@2
      displayName: Set .NET to $(Dotnet_Version)
      inputs:
        version: $(Dotnet_Version).x 

    - template: base/dotnet-main.yml
      parameters:
        testsDirectory: ${{parameters.testsDirectory}}    
      
    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: false
        projects: ${{parameters.workingDirectory}}/*.csproj
        arguments: --output $(Build.ArtifactStagingDirectory)/$(WebAppName)
        zipAfterPublish: true    

    - template: base/ef-migrate.yml
      parameters:
        efMigrations: ${{parameters.efMigrations}}

    - task: AzureWebApp@1
      displayName: Azure Web app deploy
      inputs:
        azureSubscription: $(ARMServiceEndpoint)
        appName: $(WebAppName)
        appType: webApp
        package: '$(Build.ArtifactStagingDirectory)/$(WebAppName)/*.zip'