parameters:
- name: workingDirectory
  type: string
- name: testsDirectory
  type: string  
  default: ''
- name: efMigrations
  type: object
  default:
    enabled: false

variables:
  - template: base/variables.yml

stages:
- stage: Main
  displayName: Build and publish

  jobs:
  - job: Main
    displayName: Build and publish

    steps:
    - task: UseDotNet@2
      displayName: Set .NET to $(Dotnet_Version)
      inputs:
        version: $(Dotnet_Version).x    

    - template: base/dotnet-main.yml
      parameters:
        testsDirectory: ${{parameters.testsDirectory}}

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: |
          ${{parameters.workingDirectory}}/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/$(WebAppName)

    - template: base/ef-migrate.yml
      parameters:
        efMigrations: ${{parameters.efMigrations}}
      
    - task: ArchiveFiles@2
      displayName: Zip files
      inputs:
        rootFolderOrFile: $(System.DefaultWorkingDirectory)/$(WebAppName)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
       
    - task: AzureFunctionApp@1
      displayName: Azure functions deploy
      inputs:
        azureSubscription: $(ARMServiceEndpoint)
        appType: functionApp
        appName: $(WebAppName)
        package: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip